DEVICE_RESOURCE_MAP={
"lumi.camera.agl002":{"switches":[{"key":"pir_video_recording","label":"pir_recording","rid":"4.86.85"},{"key":"tamper_video_recording","label":"tamper_recording","rid":"4.90.85"},{"key":"high_temp_alarm","label":"high_temp_alarm","rid":"4.67.85"},{"key":"face_push","label":"face_push","rid":"4.55.85"},{"key":"anti_tamper_alarm","label":"anti_tamper_alarm","rid":"4.66.85"},{"key":"face_video_recording","label":"face_recording","rid":"4.54.85"},{"key":"privacy_mode","label":"privacy_mode","rid":"14.125.85"},{"key":"doorbell_notification","label":"doorbell_notification","rid":"4.154.85"},{"key":"doorbell_video_recording","label":"doorbell_recording","rid":"4.138.85"},{"key":"low_temp_alarm","label":"low_temp_alarm","rid":"4.68.85"}],"numbers":[{"key":"doorbell_volume","label":"doorbell_volume","rid":"14.2.1000","min":0,"max":100,"step":1},{"key":"alarm_volume","label":"alarm_volume","rid":"14.1.1000","min":0,"max":100,"step":1},{"key":"camera_volume","label":"camera_volume","rid":"14.65.85","min":0,"max":100,"step":1}],"sensors":[{"key":"battery","label":"battery","rid":"8.0.2001","unit":"%","device_class":"battery"},{"key":"doorbell_status","label":"doorbell_status","rid":"13.12.85","event_status":"doorbell"},{"key":"face_recognition_event","label":"recognized_person","rid":"13.95.85","face_map":True},{"key":"tamper_status","label":"tamper_status","rid":"13.9.85","event_status":"tamper"},{"key":"high_temp_status","label":"high_temp_status","rid":"13.10.85","event_status":"problem"},{"key":"low_temp_status","label":"low_temp_status","rid":"13.11.85","event_status":"problem"}],"binary_sensors":[]},
"lumi.gateway.agl004":{"switches":[{"key":"accidental_deletion_prevention","label":"accidental_deletion","rid":"8.0.2158"}],"numbers":[{"key":"music_volume","label":"music_volume","rid":"14.3.1000","min":0,"max":100,"step":1},{"key":"doorbell_volume","label":"doorbell_volume","rid":"14.2.1000","min":0,"max":100,"step":1},{"key":"alarm_volume","label":"alarm_volume","rid":"14.1.1000","min":0,"max":100,"step":1},{"key":"system_volume","label":"system_volume","rid":"14.11.85","min":0,"max":100,"step":1},{"key":"alarm_duration","label":"alarm_duration","rid":"14.1.113","min":-1,"max":255,"step":1},{"key":"doorbell_duration","label":"doorbell_duration","rid":"14.2.113","min":-1,"max":255,"step":1}],"sensors":[{"key":"restart_count","label":"restart_count","rid":"8.0.2002","diagnostic":True},{"key":"temperature_internal","label":"internal_temperature","rid":"8.0.2006"},{"key":"wifi_channel","label":"wifi_channel","rid":"8.0.2025","diagnostic":True},{"key":"restart_reason","label":"restart_reason","rid":"8.0.2029","diagnostic":True},{"key":"music_status","label":"music_status","rid":"14.3.111"},{"key":"binding_status","label":"binding_status","rid":"8.0.8107","diagnostic":True},{"key":"humidity","label":"humidity","rid":"0.2.85","unit":"%","scale":0.01,"device_class":"humidity"},{"key":"temperature","label":"temperature","rid":"0.1.85","unit":"°C","scale":0.01,"device_class":"temperature"},{"key":"alarm_status","label":"alarm_status","rid":"14.1.111"}],"binary_sensors":[{"key":"device_online_resource","label":"device_online_resource","rid":"8.0.2045","on":"1","diagnostic":True}]}}
U200_MODEL="aqara.matter.4447_10242"
U200_LOCK={"endpoint_id":2,"function_code":"DoorLock","trait_code":"LockState"}
U200_POWER_TRAITS=[{"key":"battery_percent","label":"battery","endpoint_id":1,"function_code":"PowerSource","trait_code":"BatPercentRemaining","unit":"%","device_class":"battery"},{"key":"current_voltage","label":"current_voltage","endpoint_id":1,"function_code":"PowerSource","trait_code":"CurrentVoltage","unit":"V","device_class":"voltage"},{"key":"low_battery","label":"low_battery","endpoint_id":1,"function_code":"PowerSource","trait_code":"StateOfLowBat"}]
CAMERA_TRAIT_MODEL="lumi.camera.acn006"
CAMERA_HUMAN_EVENT_RID="13.97.85"
CAMERA_TRAIT_SWITCHES=[]; CAMERA_TRAIT_SENSORS=[]; CAMERA_TRAIT_BINARY_SENSORS=[]
